apps/neoscan_web/lib/neoscan_web/router.ex
defmodule NeoscanWeb.Router do
  use NeoscanWeb, :router
  alias NeoscanWeb.Plugs.Locale
  alias NeoscanWeb.Plugs.Tooltip

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(Locale)
    plug(Tooltip)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  forward("/wobserver", Wobserver.Web.Router)

  scope "/", NeoscanWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)
    post("/", HomeController, :search)
    get("/address/:address", AddressController, :index)
    get("/address/:address/:page", AddressController, :go_to_page)
    get("/addresses/1", AddressesController, :index)
    get("/addresses/:page", AddressesController, :go_to_page)
    get("/block/:hash", BlockController, :index)
    get("/block/:hash/:page", BlockController, :go_to_page)
    get("/blocks/1", BlocksController, :index)
    get("/blocks/:page", BlocksController, :go_to_page)
    get("/doc", DocController, :index)
    get("/price/:from/:to/:graph", PriceController, :index)
    get("/transaction/:txid", TransactionController, :index)
    get("/transactions/1", TransactionsController, :index)
    get("/transactions/:page", TransactionsController, :go_to_page)
    get("/transactions/type/:type/:page", TransactionsController, :filtered_transactions)
    get("/transfers/1", TransfersController, :index)
    get("/transfers/:page", TransfersController, :go_to_page)
  end

  scope "/api/main_net/v1", NeoscanWeb do
    pipe_through(:api)

    get("/get_balance/:hash", ApiController, :get_balance)
    get("/get_claimed/:hash", ApiController, :get_claimed)
    get("/get_unclaimed/:hash", ApiController, :get_unclaimed)
    get("/get_claimable/:hash", ApiController, :get_claimable)
    get("/get_address/:hash", ApiController, :get_address)
    get("/get_address_neon/:hash", ApiController, :get_address_neon)
    get("/get_assets", ApiController, :get_assets)
    get("/get_asset/:hash", ApiController, :get_asset)
    get("/get_block/:hash", ApiController, :get_block)
    get("/get_last_blocks", ApiController, :get_last_blocks)
    get("/get_highest_block", ApiController, :get_highest_block)
    get("/get_last_transactions", ApiController, :get_last_transactions)
    get("/get_last_transactions/:type", ApiController, :get_last_transactions)

    get(
      "/get_last_transactions_by_address/:hash/:page",
      ApiController,
      :get_last_transactions_by_address
    )

    get(
      "/get_last_transactions_by_address/:hash",
      ApiController,
      :get_last_transactions_by_address
    )

    get("/get_transaction/:hash", ApiController, :get_transaction)
    get("/get_all_nodes", ApiController, :get_all_nodes)
    get("/get_height", ApiController, :get_height)
    get("/get_nodes", ApiController, :get_nodes)
    get("/get_fees_in_range/:range", ApiController, :get_fees_in_range)
    get("/repair_blocks", ApiController, :repair_blocks)
    get("/repair_block_counter", ApiController, :repair_block_counter)
    get("/get_address_abstracts/:hash/:page", ApiController, :get_address_abstracts)

    get(
      "/get_address_to_address_abstracts/:hash1/:hash2/:page",
      ApiController,
      :get_address_to_address_abstracts
    )
  end

  # Other scopes may use custom stacks.
  # scope "/api", NeoscanWeb do
  #   pipe_through :api
  # end
end

apps/neoscan_web/lib/neoscan_web/controllers/transaction_controller.ex
defmodule NeoscanWeb.TransactionController do
  use NeoscanWeb, :controller

  alias Neoscan.Transactions
  alias Neoscan.Transfers

  def index(conn, %{"txid" => transaction_hash}) do
    tran = Transactions.get_transaction_by_hash_for_view(transaction_hash)

    case tran do
      nil ->
        route(nil, conn)

      _ ->
        new_vin = clean_list(tran.vin)

        new_claim = clean_list(tran.claims)

        new_asset = clean_map(tran.asset)

        transfers = Transfers.get_transaction_transfers(transaction_hash)

        Map.merge(tran, %{
          :vin => new_vin,
          :claims => new_claim,
          :asset => new_asset,
          :transfers => transfers
        })
        |> route(conn)
    end
  end

  def route(nil, conn) do
    conn
    |> put_flash(:info, "Not Found in DB!")
    |> redirect(to: home_path(conn, :index))
  end

  def route(transaction, conn) do
    render(conn, "transaction.html", transaction: transaction)
  end

  defp clean_list(nil) do
    nil
  end

  defp clean_list(list) do
    Enum.map(list, fn l ->
      {:ok, new_l} = Morphix.atomorphiform(l)
      new_l
    end)
  end

  defp clean_map(nil) do
    nil
  end

  defp clean_map(map) do
    {:ok, new_map} = Morphix.atomorphiform(map)
    new_map
  end
end

apps/neoscan_web/lib/neoscan_web/controllers/transactions_controller.ex
defmodule NeoscanWeb.TransactionsController do
  use NeoscanWeb, :controller

  alias NeoscanCache.Api, as: CacheApi
  alias Neoscan.Transactions
  alias Neoscan.Transfers

  def index(conn, _params) do
    transactions =
      CacheApi.get_transactions()
      |> Enum.map(fn transaction ->
        {:ok, result} = Morphix.atomorphiform(transaction)
        result
      end)

    transfers =
      Enum.map(transactions, fn tx -> tx.txid end)
      |> Transfers.get_transactions_transfers()

    transactions =
      transactions
      |> Enum.map(fn tx ->
        Map.merge(tx, %{
          :transfers =>
            Enum.filter(transfers, fn transfer ->
              transfer.txid == tx.txid
            end) || []
        })
      end)

    render(conn, "transactions.html", transactions: transactions, page: "1", type: nil)
  end

  def go_to_page(conn, %{"page" => page}) do
    transactions =
      Transactions.paginate_transactions(page)
      |> Enum.map(fn transaction ->
        {:ok, result} = Morphix.atomorphiform(transaction)
        result
      end)

    transfers =
      Enum.map(transactions, fn tx -> tx.txid end)
      |> Transfers.get_transactions_transfers()

    transactions =
      transactions
      |> Enum.map(fn tx ->
        Map.merge(tx, %{
          :transfers =>
            Enum.filter(transfers, fn transfer ->
              transfer.txid == tx.txid
            end) || []
        })
      end)

    render(conn, "transactions.html", transactions: transactions, page: page, type: nil)
  end

  def filtered_transactions(conn, %{"type" => type, "page" => page}) do
    transactions =
      Transactions.paginate_transactions(page, [type])
      |> Enum.map(fn transaction ->
        {:ok, result} = Morphix.atomorphiform(transaction)
        result
      end)

    transfers =
      Enum.map(transactions, fn tx -> tx.txid end)
      |> Transfers.get_transactions_transfers()

    transactions =
      transactions
      |> Enum.map(fn tx ->
        Map.merge(tx, %{
          :transfers =>
            Enum.filter(transfers, fn transfer ->
              transfer.txid == tx.txid
            end) || []
        })
      end)

    render(conn, "transactions.html", transactions: transactions, page: page, type: type)
  end
end

apps/neoscan_web/lib/neoscan_web/views/transaction_view.ex
defmodule NeoscanWeb.TransactionView do
  use NeoscanWeb, :view
  use Timex
  import Number.Delimit
  alias Neoscan.Vm.Disassembler
  alias Neoscan.Helpers
  alias Neoscan.Explanations
  alias NeoscanWeb.ViewHelper
  alias Neoscan.ChainAssets
  alias NeoscanCache.Api, as: CacheApi

  def get_type("MinerTransaction"), do: 'Miner'
  def get_type("ContractTransaction"), do: 'Contract'
  def get_type("ClaimTransaction"), do: 'GAS Claim'
  def get_type("IssueTransaction"), do: 'Asset Issue'
  def get_type("RegisterTransaction"), do: 'Asset Register'
  def get_type("InvocationTransaction"), do: 'Contract Invocation'
  def get_type("PublishTransaction"), do: 'Contract Publish'
  def get_type("EnrollmentTransaction"), do: 'Enrollment'
  def get_type("StateTransaction"), do: 'State'

  def get_icon("MinerTransaction"), do: 'fa-user-circle-o'
  def get_icon("ContractTransaction"), do: 'fa-cube'
  def get_icon("ClaimTransaction"), do: 'fa-cubes'
  def get_icon("IssueTransaction"), do: 'fa-handshake-o'
  def get_icon("RegisterTransaction"), do: 'fa-list-alt'
  def get_icon("InvocationTransaction"), do: 'fa-paper-plane'
  def get_icon("EnrollmentTransaction"), do: 'fa-paper-plane'
  def get_icon("StateTransaction"), do: 'fa-list-alt'
  def get_icon("PublishTransaction"), do: 'Contract Publish'

  def compare_time_and_get_minutes(time) do
    ViewHelper.compare_time_and_get_minutes(time)
  end

  def parse_invocation(nil) do
    "No Invocation Script"
  end

  def parse_invocation(script) do
    %{"invocation" => inv} = script

    Disassembler.parse_script(inv)
  end

  def parse_verification(nil) do
    "No Verification Script"
  end

  def parse_verification(script) do
    %{"verification" => ver} = script

    Disassembler.parse_script(ver)
  end

  def get_inv(nil) do
    "No Invocation Script"
  end

  def get_inv(%{"invocation" => inv}) do
    inv
  end

  def get_ver(nil) do
    "No Verification Script"
  end

  def get_ver(%{"verification" => ver}) do
    ver
  end

  def get_explanation(topic) do
    Explanations.get(topic)
  end

  def get_tooltips(conn) do
    ViewHelper.get_tooltips(conn)
  end

  def apply_precision(asset, amount) do
    precision = ChainAssets.get_asset_precision_by_hash(asset)

    amount
    |> Helpers.apply_precision(asset, precision)
  end
end

apps/neoscan_web/lib/neoscan_web/views/transactions_view.ex
defmodule NeoscanWeb.TransactionsView do
  use NeoscanWeb, :view
  import Number.Delimit
  alias NeoscanCache.Api, as: CacheApi
  alias Neoscan.Helpers
  alias Neoscan.ChainAssets

  def get_class("ContractTransaction"), do: 'neo-transaction'
  def get_class("ClaimTransaction"), do: 'gas-transaction'
  def get_class("IssueTransaction"), do: 'issue-transaction'
  def get_class("RegisterTransaction"), do: 'register-transaction'
  def get_class("InvocationTransaction"), do: 'invocation-transaction'
  def get_class("EnrollmentTransaction"), do: 'invocation-transaction'
  def get_class("StateTransaction"), do: 'invocation-transaction'
  def get_class("PublishTransaction"), do: 'publish-transaction'
  def get_class("MinerTransaction"), do: 'miner-transaction'

  def get_current_min_qtd(page, type) do
    %{:total_transactions => [filtered_totals, total, _total_transfers]} = CacheApi.get_stats()

    total =
      case type do
        nil -> total
        txType -> Map.get(filtered_totals, String.capitalize(txType) <> "Transaction")
      end

    if total == 0 do
      1
    else
      (String.to_integer(page) - 1) * 15 + 1
    end
  end

  def get_current_max_qtd(page, type) do
    %{:total_transactions => [filtered_totals, total, _total_transfers]} = CacheApi.get_stats()

    total =
      case type do
        nil -> total
        txType -> Map.get(filtered_totals, String.capitalize(txType) <> "Transaction")
      end

    cond do
      total < 15 ->
        total

      String.to_integer(page) * 15 > total ->
        total

      true ->
        String.to_integer(page) * 15
    end
  end

  def get_previous_page(conn, page, type) do
    int =
      page
      |> String.to_integer()

    num =
      (int - 1)
      |> Integer.to_string()

    if type do
      raw(
        '<a href="#{transactions_path(conn, :filtered_transactions, type, num)}" class="button btn btn-primary"><i class="fa fa-angle-left"></i></a>'
      )
    else
      raw(
        '<a href="#{transactions_path(conn, :go_to_page, num)}" class="button btn btn-primary"><i class="fa fa-angle-left"></i></a>'
      )
    end
  end

  def get_next_page(conn, page, type) do
    int =
      page
      |> String.to_integer()

    num =
      (int + 1)
      |> Integer.to_string()

    if type do
      raw(
        '<a href="#{transactions_path(conn, :filtered_transactions, type, num)}" class="button btn btn-primary"><i class="fa fa-angle-right"></i></a>'
      )
    else
      raw(
        '<a href="#{transactions_path(conn, :go_to_page, num)}" class="button btn btn-primary"><i class="fa fa-angle-right"></i></a>'
      )
    end
  end

  def check_last(page, type) do
    int =
      page
      |> String.to_integer()

    %{:total_transactions => [filtered_totals, total, _total_transfers]} = CacheApi.get_stats()

    total =
      case type do
        nil -> total
        txType -> Map.get(filtered_totals, String.capitalize(txType) <> "Transaction")
      end

    if int * 15 < total do
      true
    else
      false
    end
  end

  def get_total(type) do
    %{:total_transactions => [filtered_totals, total, _total_transfers]} = CacheApi.get_stats()

    if type do
      Map.get(filtered_totals, String.capitalize(type) <> "Transaction")
    else
      total
    end
  end

  def apply_precision(asset, amount) do
    precision = ChainAssets.get_asset_precision_by_hash(asset)

    amount
    |> Helpers.apply_precision(asset, precision)
  end
end

apps/neoscan_web/lib/neoscan_web/templates/transaction/transaction.html.eex
<h1 class="content-title"><%= gettext "Transaction Information"%></h1>

<p class="large-detail-text">
  <span class="fa <%= get_icon(@transaction.type) %>"></span>
  <span class="bold-text"><%= get_type(@transaction.type) %></span>
  <span class="green-bar">|</span> <span class="bold-text">Hash:</span>
  <span class="eggshell-blue-text hash"><%= @transaction.txid %></span>
</p>

<a href="<%= transactions_path(@conn, :index) %>" alt="<%= gettext "Back to all transactions"%>" title="<%= gettext "Back to all transactions"%>" class="back-link"><%= gettext "Back to all transactions" %></a>

<section id="asset-information" class="corner-box bar-left-transactions">

	<!-- Transaction panel -->
	<div class="transaction-panel">
    <%= if @transaction.vin != [] or @transaction.claims != [] or @transaction.vouts != [] do %>
  		<div class="sent-from-wrapper">
        <%= if @transaction.type == "ClaimTransaction" do %>
          <p class="large-detail-text"><%= gettext "Claimed from" %></p>
          <%= for input <- @transaction.claims do %>
            <div class="individual-transaction">
              <a href="<%= address_path(@conn, :index, input.address_hash)%>" alt="<%= gettext "View wallet address"%>" title="<%= gettext "View wallet address"%>" class="large-blue-link wallet-address"><span class="fa fa-key"></span><%= input.address_hash %></a>
              <p class="neo-amount large-blue-link"><span class="fa fa-cubes"></span><%= Helpers.round_or_not(input.value) %> <%= CacheApi.get_asset_name(input.asset) %></p>
            </div>
          <% end %>
        <% end %>
        <%= if @transaction.type != "ClaimTransaction" and @transaction.vin != []  do %>
    			<p class="large-detail-text"><%= gettext "Sent from" %></p>
          <%= for input <- @transaction.vin do %>
      			<div class="individual-transaction">
      				<a href="<%= address_path(@conn, :index, input.address_hash)%>" alt="<%= gettext "View wallet address"%>" title="<%= gettext "View wallet address"%>" class="large-blue-link wallet-address"><span class="fa fa-key"></span><%= input.address_hash %></a>
      				<p class="neo-amount large-blue-link"><span class="fa fa-cubes"></span><%= Helpers.round_or_not(input.value) %> <%= CacheApi.get_asset_name(input.asset) %></p>
      			</div>
          <% end %>
        <% end %>
  		</div>
  		<img src="<%= static_path(@conn, "/images/ICON_Sent-arrow.svg")%>" class="transaction-sent-arrow" />
      <div class="sent-to-wrapper">
        <%= if @transaction.vouts != [] do %>
      	  <p class="large-detail-text"><%= gettext "Sent to" %></p>
          <%= for vout <- @transaction.vouts do %>
      			<div class="individual-transaction">
      				<a href="<%= address_path(@conn, :index, vout.address_hash)%>" alt="<%= gettext "View wallet address"%>" title="<%= gettext "View wallet address"%>" class="large-blue-link wallet-address"><span class="fa fa-key"></span><%= vout.address_hash %></a>
      				<p class="gas-amount large-blue-link"><span class="fa fa-cube"></span><%= Helpers.round_or_not(vout.value) %> <%= CacheApi.get_asset_name(vout.asset) %></p>
      			</div>
          <% end %>
        <% end %>
        <%= if @transaction.type == "RegisterTransaction" do %>
          <p class="large-detail-text"><%= gettext "Registered" %></p>
          <div class="individual-transaction">
            <a href="<%= address_path(@conn, :index, @transaction.asset.admin)%>" alt="<%= gettext "View wallet address"%>" title="<%= gettext "View wallet address"%>" class="large-blue-link wallet-address"><span class="fa fa-key"></span><%= @transaction.asset.admin %></a>
            <p class="gas-amount large-blue-link"><span class="fa fa-cube"></span><%= Helpers.round_or_not(@transaction.asset.amount) %> <%= CacheApi.get_asset_name(@transaction.txid) %></p>
          </div>
        <% end %>
      </div>
    <% end %>
	</div>

	<!-- Extra information list -->
	<ul id="extra-information">
		<li class="border-right border-bottom border-right-smaller min-height-97px remove-border-right-660px tooltip <%= if get_tooltips(@conn) == "on" do %>add-hover<% end %>">
			<p class="small-detail-text"><%= gettext "Time" %></p>
			<p class="large-detail-text"><%= compare_time_and_get_minutes(@transaction.time) %></p>
      <span class="tooltiptext"><%= get_explanation("transaction_time") %></span>
		</li>
		<li class="border-right border-bottom min-height-97px tooltip">
			<p class="small-detail-text"><%= gettext "Network Fee" %></p>
			<p class="large-detail-text"><%= @transaction.net_fee %></p>
      <span class="tooltiptext"><%= get_explanation("transaction_network_fees") %></span>
		</li>
		<li class="border-bottom border-right-smaller min-height-97px remove-border-right-660px tooltip <%= if get_tooltips(@conn) == "on" do %>add-hover<% end %>">
			<p class="small-detail-text"><%= gettext "System Fee" %></p>
			<p class="large-detail-text"><%= number_to_delimited(@transaction.sys_fee) %></p>
      <span class="tooltiptext"><%= get_explanation("transaction_system_fees") %></span>
		</li>
		<li class="border-right border-right-smaller min-height-97px remove-border-right-660px">
			<p class="small-detail-text"><%= gettext "Included in Block" %></p>
			<p class="large-detail-text"><a href="<%= block_path( @conn, :index, @transaction.block_hash) %>" alt="<%= gettext "View block"%>" title="<%= gettext "View block"%>" class="large-blue-link col-4-width"><%= number_to_delimited(@transaction.block_height) %></a></p>
		</li>
		<li class="min-height-97px border-right remove-border-bottom-660px border-bottom-smaller tooltip <%= if get_tooltips(@conn) == "on" do %>add-hover<% end %>">
			<p class="small-detail-text"><%= gettext "Size" %></p>
			<p class="large-detail-text"><%= number_to_delimited(@transaction.size) %> <%= gettext "bytes" %></p>
      <span class="tooltiptext"><%= get_explanation("transaction_size") %></span>
		</li>
	</ul>

</section>


<!-- Transfers panel -->
<%= if @transaction.transfers != [] do %>
  <h2><%= gettext "Transfers" %></h2>
  <section id="asset-information" class="corner-box bar-left-transactions">
    <%= for transfer <- @transaction.transfers do %>
      <div class="transaction-panel">
        <div class="sent-from-wrapper">
          <p class="large-detail-text"><%= gettext "Sent from" %></p>
          <div class="individual-transaction">
            <a href="<%= address_path(@conn, :index, transfer.address_from)%>" alt="<%= gettext "View wallet address"%>" title="<%= gettext "View wallet address"%>" class="large-blue-link wallet-address"><span class="fa fa-key"></span><%= transfer.address_from %></a>
            <p class="neo-amount large-blue-link"><span class="fa fa-cubes"></span><%= Helpers.round_or_not(apply_precision(transfer.contract,transfer.amount)) %> <%= CacheApi.get_asset_name(transfer.contract) %></p>
          </div>
        </div>
        <img src="<%= static_path(@conn, "/images/ICON_Sent-arrow.svg")%>" class="transaction-sent-arrow" />
        <div class="sent-to-wrapper">
          <p class="large-detail-text"><%= gettext "Sent to" %></p>
          <div class="individual-transaction">
            <a href="<%= address_path(@conn, :index, transfer.address_to)%>" alt="<%= gettext "View wallet address"%>" title="<%= gettext "View wallet address"%>" class="large-blue-link wallet-address"><span class="fa fa-key"></span><%= transfer.address_to %></a>
            <p class="gas-amount large-blue-link"><span class="fa fa-cube"></span><%= Helpers.round_or_not(apply_precision(transfer.contract,transfer.amount)) %> <%= CacheApi.get_asset_name(transfer.contract) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </section>
<% end %>

<ul id="bytecode-invocation-list">
  <%= if @transaction.contract != nil do %>
		<li class="corner-box">
			<h2><%= gettext "Contract" %></h2>
			<div class="corner-box">
				<p class="small-detail-text bar-left-transactions"><%= Poison.encode!(@transaction.contract) %></p>
			</div>
		</li>
  <% end %>
</ul>

<ul id="bytecode-invocation-list">
	<li class="corner-box remove-margin-left">
    <div class="tooltip <%= if get_tooltips(@conn) == "on" do %>add-hover<% end %>">
      <h2><%= gettext "Bytecode Invocation Script" %></h2>
      <span class="tooltiptext"><%= get_explanation("bytecode_invocation_script") %></span>
    </div>
		<div class="corner-box">
			<%= for script <- @transaction.scripts do %>
			  <p class="small-detail-text bar-left-transactions"><%= get_inv(script) %></p>
			<% end %>
		</div>
	</li>
	<li class="corner-box">
    <div class="tooltip <%= if get_tooltips(@conn) == "on" do %>add-hover<% end %>">
      <h2><%= gettext "Bytecode Verification Script" %></h2>
      <span class="tooltiptext"><%= get_explanation("bytecode_verification_script") %></span>
    </div>
		<div class="corner-box">
			<%= for script <- @transaction.scripts do %>
			  <p class="small-detail-text bar-left-transactions"><%= get_ver(script) %></p>
			<% end %>
		</div>
	</li>
</ul>

<ul id="bytecode-invocation-list">
  <%= if @transaction.attributes != [] do %>
		<%= for att <- @transaction.attributes do %>
			<li class="corner-box remove-margin-left">
				<h2><%= gettext "Atributte" %>: <%=att["usage"]%></h2>
				<div class="corner-box">
					<p class="small-detail-text bar-left-transactions"><%= att["data"] %></p>
				</div>
			</li>
		<% end %>
  <% end %>
  <%= if @transaction.script != nil do %>
		<li class="corner-box">
			<h2><%= gettext "Bytecode Script" %></h2>
			<div class="corner-box">
				<p class="small-detail-text bar-left-transactions"><%= @transaction.script %></p>
			</div>
		</li>
  <% end %>
</ul>

<ul id="bytecode-invocation-list">
	<li class="corner-box remove-margin-left">
    <div class="tooltip <%= if get_tooltips(@conn) == "on" do %>add-hover<% end %>">
      <h2><%= gettext "Opcode Invocation Script" %></h2>
      <span class="tooltiptext"><%= get_explanation("opcode_invocation_script") %></span>
    </div>
		<div class="corner-box">
			<p class="small-detail-text bar-left-transactions">
        <%= for script <- @transaction.scripts do %>
          <%= for operation <- parse_invocation(script) do %>
            <span class="script-new-line"><%= operation %></span>
          <% end %>
        <% end %>
      </p>
		</div>
	</li>
	<li class="corner-box">
    <div class="tooltip <%= if get_tooltips(@conn) == "on" do %>add-hover<% end %>">
      <h2><%= gettext "Opcode Verification Script" %></h2>
      <span class="tooltiptext"><%= get_explanation("opcode_verification_script") %></span>
    </div>
		<div class="corner-box">
			<p class="small-detail-text bar-left-transactions">
        <%= for script <- @transaction.scripts do %>
          <%= for operation <- parse_verification(script) do %>
            <span class="script-new-line"><%= operation %></span>
          <% end %>
        <% end %>
      </p>
		</div>
	</li>
</ul>

<ul id="bytecode-invocation-list">
  <%= if @transaction.script != nil do %>
		<li class="corner-box remove-margin-left">
			<h2><%= gettext "Opcode Script" %></h2>
			<div class="corner-box">
        <p class="small-detail-text bar-left-transactions">
          <%= for operation <- Disassembler.parse_script(@transaction.script) do %>
  				  <span class="script-new-line"><%= operation %></span>
          <% end %>
        </p>
			</div>
		</li>
  <% end %>
</ul>