apps/neoscan_web/lib/neoscan_web/router.ex
defmodule NeoscanWeb.Router do
  use NeoscanWeb, :router
  alias NeoscanWeb.Plugs.Locale
  alias NeoscanWeb.Plugs.Tooltip

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(Locale)
    plug(Tooltip)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  forward("/wobserver", Wobserver.Web.Router)

  scope "/", NeoscanWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)
    post("/", HomeController, :search)
    get("/address/:address", AddressController, :index)
    get("/address/:address/:page", AddressController, :go_to_page)
    get("/addresses/1", AddressesController, :index)
    get("/addresses/:page", AddressesController, :go_to_page)
    get("/block/:hash", BlockController, :index)
    get("/block/:hash/:page", BlockController, :go_to_page)
    get("/blocks/1", BlocksController, :index)
    get("/blocks/:page", BlocksController, :go_to_page)
    get("/doc", DocController, :index)
    get("/price/:from/:to/:graph", PriceController, :index)
    get("/transaction/:txid", TransactionController, :index)
    get("/transactions/1", TransactionsController, :index)
    get("/transactions/:page", TransactionsController, :go_to_page)
    get("/transactions/type/:type/:page", TransactionsController, :filtered_transactions)
    get("/transfers/1", TransfersController, :index)
    get("/transfers/:page", TransfersController, :go_to_page)
  end

  scope "/api/main_net/v1", NeoscanWeb do
    pipe_through(:api)

    get("/get_balance/:hash", ApiController, :get_balance)
    get("/get_claimed/:hash", ApiController, :get_claimed)
    get("/get_unclaimed/:hash", ApiController, :get_unclaimed)
    get("/get_claimable/:hash", ApiController, :get_claimable)
    get("/get_address/:hash", ApiController, :get_address)
    get("/get_address_neon/:hash", ApiController, :get_address_neon)
    get("/get_assets", ApiController, :get_assets)
    get("/get_asset/:hash", ApiController, :get_asset)
    get("/get_block/:hash", ApiController, :get_block)
    get("/get_last_blocks", ApiController, :get_last_blocks)
    get("/get_highest_block", ApiController, :get_highest_block)
    get("/get_last_transactions", ApiController, :get_last_transactions)
    get("/get_last_transactions/:type", ApiController, :get_last_transactions)

    get(
      "/get_last_transactions_by_address/:hash/:page",
      ApiController,
      :get_last_transactions_by_address
    )

    get(
      "/get_last_transactions_by_address/:hash",
      ApiController,
      :get_last_transactions_by_address
    )

    get("/get_transaction/:hash", ApiController, :get_transaction)
    get("/get_all_nodes", ApiController, :get_all_nodes)
    get("/get_height", ApiController, :get_height)
    get("/get_nodes", ApiController, :get_nodes)
    get("/get_fees_in_range/:range", ApiController, :get_fees_in_range)
    get("/repair_blocks", ApiController, :repair_blocks)
    get("/repair_block_counter", ApiController, :repair_block_counter)
    get("/get_address_abstracts/:hash/:page", ApiController, :get_address_abstracts)

    get(
      "/get_address_to_address_abstracts/:hash1/:hash2/:page",
      ApiController,
      :get_address_to_address_abstracts
    )
  end

  # Other scopes may use custom stacks.
  # scope "/api", NeoscanWeb do
  #   pipe_through :api
  # end
end

apps/neoscan_web/lib/neoscan_web/controllers/transfers_controller.ex
defmodule NeoscanWeb.TransfersController do
  use NeoscanWeb, :controller

  alias NeoscanCache.Api, as: CacheApi
  alias Neoscan.Transfers

  def index(conn, _params) do
    transfers =
      CacheApi.get_transfers()
      |> Enum.map(fn transfer ->
        {:ok, result} = Morphix.atomorphiform(transfer)
        result
      end)

    render(conn, "transfers.html", transfers: transfers, page: "1", type: nil)
  end

  def go_to_page(conn, %{"page" => page}) do
    transfers =
      Transfers.paginate_transfers(page)
      |> Enum.map(fn transfer ->
        {:ok, result} = Morphix.atomorphiform(transfer)
        result
      end)

    render(conn, "transfers.html", transfers: transfers, page: page, type: nil)
  end
end

apps/neoscan_web/lib/neoscan_web/views/transfers_view.ex
defmodule NeoscanWeb.TransfersView do
  use NeoscanWeb, :view
  import Number.Delimit
  alias NeoscanCache.Api, as: CacheApi
  alias Neoscan.Helpers
  alias Neoscan.ChainAssets

  def get_current_min_qtd(page) do
    %{:total_transfers => total} = CacheApi.get_stats()

    if total == 0 do
      1
    else
      (String.to_integer(page) - 1) * 15 + 1
    end
  end

  def get_current_max_qtd(page) do
    %{:total_transfers => total} = CacheApi.get_stats()

    cond do
      total < 15 ->
        total

      String.to_integer(page) * 15 > total ->
        total

      true ->
        String.to_integer(page) * 15
    end
  end

  def get_previous_page(conn, page) do
    int =
      page
      |> String.to_integer()

    num =
      (int - 1)
      |> Integer.to_string()

    raw(
      '<a href="#{transfers_path(conn, :go_to_page, num)}" class="button btn btn-primary"><i class="fa fa-angle-left"></i></a>'
    )
  end

  def get_next_page(conn, page) do
    int =
      page
      |> String.to_integer()

    num =
      (int + 1)
      |> Integer.to_string()

    raw(
      '<a href="#{transfers_path(conn, :go_to_page, num)}" class="button btn btn-primary"><i class="fa fa-angle-right"></i></a>'
    )
  end

  def check_last(page) do
    int =
      page
      |> String.to_integer()

    %{:total_transfers => total} = CacheApi.get_stats()

    if int * 15 < total do
      true
    else
      false
    end
  end

  def get_total() do
    %{:total_transfers => total} = CacheApi.get_stats()

    total
  end

  def apply_precision(asset, amount) do
    precision = ChainAssets.get_asset_precision_by_hash(asset)

    amount
    |> Helpers.apply_precision(asset, precision)
  end
end

apps/neoscan_web/lib/neoscan_web/templates/transfers/transfers.html.eex
<h1 class="transactions-content-title"><%= gettext "Transfers"%></h1>

<!-- All transactions content -->
<section id="all-transactions-wrapper">

  <div class="detail-bar">
    <p class="detail-type detail-type-first-2-col"><%= gettext "Type" %></p>
    <p class="detail-type col-6-width"><%= gettext "Transaction ID" %></p>
    <p class="detail-type col-2-width"><%= gettext "Completed on" %></p>
    <p class="detail-type tablet-full-width"><%= gettext "All transaction information"%></p>
  </div>

  <!-- Transactions -->
  <section id="transactions-wrapper">

    <div class="transactions-list">

      <%= for transaction <- @transfers do %>
        <div class="full-width-bar invocation-transaction">
          <div class="information-wrapper">
            <p class="medium-detail-text col-2-width"><span class="fa fa-paper-plane"></span><%= gettext "Transfer" %></p>
            <div class="secondary-info-wrapper">
              <a href="<%=transaction_path(@conn, :index, transaction.txid )%>" alt="<%= gettext "View transaction"%>" title="<%= gettext "View transaction"%>" class="large-blue-link col-6-width"><%=transaction.txid%>&#8230;</a>
              <p class="medium-detail-text col-2-width remove-550px">
                <%=
                  {:ok, date_time} = DateTime.from_unix(transaction.time, :second)
                  DateTime.to_date(date_time)
                %> |
                <%=
                  {:ok, date_time} = DateTime.from_unix(transaction.time, :second)
                  DateTime.to_time(date_time)
                %>
              </p>
            </div>
          </div>
          <button class="btn-accordion"><img src="<%= static_path(@conn, "/images/ICON_DownArrow.svg") %>" class="accordion-down-arrow" width="13px" height="8px" /></button>
          <div class="transaction-panel">
            <div class="sent-from-wrapper">
                <p class="large-detail-text"><%= gettext "Sent from" %></p>
                <div class="individual-transaction">
                  <a href='<%= address_path(@conn, :index, transaction.address_from)%>' alt="<%= gettext "View wallet address"%>" title="<%= gettext "View wallet address"%>" class="large-blue-link wallet-address"><span class="fa fa-key"></span><%= transaction.address_from %></a>
                  <p class="neo-amount large-blue-link"><span class="fa fa-cube"></span><%= Helpers.round_or_not(apply_precision(transaction.contract,transaction.amount)) %> <%= CacheApi.get_asset_name(transaction.contract) %></p>
                </div>
            </div>
            <img src="<%= static_path(@conn, "/images/ICON_Sent-arrow.svg")%>" class="transaction-sent-arrow" />
            <div class="sent-to-wrapper">
              <p class="large-detail-text"><%= gettext "Sent to" %></p>
              <div class="individual-transaction">
                <a href='<%= address_path(@conn, :index, transaction.address_to)%>' alt="<%= gettext "View wallet address"%>" title="<%= gettext "View wallet address"%>" class="large-blue-link wallet-address"><span class="fa fa-key"></span><%= transaction.address_to %></a>
                <p class="gas-amount large-blue-link"><span class="fa fa-cube"></span><%= Helpers.round_or_not(apply_precision(transaction.contract,transaction.amount)) %> <%= CacheApi.get_asset_name(transaction.contract) %></p>
              </div>
            </div>
          </div>
        </div>
      <%end%>

    </div>

  </section>

  <p  class="number-counter"><%= gettext "Transfers"%> <%= get_current_min_qtd(@page) %> <%= gettext "to"%> <%= get_current_max_qtd(@page) %> <%= gettext "of"%> <%= number_to_delimited(get_total()) %></p>
  <div class="see-all-button-container">
    <div class="btn-group">
      <%= if @page != "1" do %>
        <%= get_previous_page(@conn, @page) %>
      <% end %>
      <%= if check_last(@page) do %>
        <%= get_next_page(@conn, @page) %>
      <% end %>
    </div>
  </div>
</section>